language: perl

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.18-shrplib"
  - "5.20"
  - "5.20-shrplib"

before_install: cpanm --notest Module::Install

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true
